apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: red
  name: red
spec:
  replicas: 3
  selector:
    matchLabels:
      run: red
  template:
    metadata:
      labels:
        run: red
    spec:
      containers:
      - image: nginx
        name: red
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
               - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists