apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-03T14:31:55Z"
  name: red
  namespace: default
  resourceVersion: "669"
  selfLink: /api/v1/namespaces/default/pods/red
  uid: f9edb634-a311-4813-804b-2dfe7e94280a
spec:
  initContainers:
    - name: Init-container-warm-up
      command:
        - sh
        - -c
        - sleep 20
      image: busybox
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-zj84d
      readOnly: true
