apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-03T10:21:34Z"
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
  resourceVersion: "957"
  selfLink: /api/v1/namespaces/default/pods/webapp-pod
  uid: b6fac0ab-1270-4e15-8440-ee1397e7fa33
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: webapp
    envFrom:
      - secretRef:
          name: db-secret
